import acresToHectares from './area/acres-to-hectares';
import acresToSquareFeet from './area/acres-to-square-feet';
import acresToSquareKilometers from './area/acres-to-square-kilometers';
import acresToSquareMeters from './area/acres-to-square-meters';
import acresToSquareYards from './area/acres-to-square-yards';
import hectaresToAcres from './area/hectares-to-acres';
import hectaresToSquareFeet from './area/hectares-to-square-feet';
import hectaresToSquareKilometers from './area/hectares-to-square-kilometers';
import hectaresToSquareMeters from './area/hectares-to-square-meters';
import hectaresToSquareYards from './area/hectares-to-square-yards';
import squareFeetToAcres from './area/square-feet-to-acres';
import squareFeetToHectares from './area/square-feet-to-hectares';
import squareFeetToSquareKilometers from './area/square-feet-to-square-kilometers';
import squareFeetToSquareMeters from './area/square-feet-to-square-meters';
import squareFeetToSquareYards from './area/square-feet-to-square-yards';
import squareKilometersToAcres from './area/square-kilometers-to-acres';
import squareKilometersToHectares from './area/square-kilometers-to-hectares';
import squareKilometersToSquareFeet from './area/square-kilometers-to-square-feet';
import squareKilometersToSquareMeters from './area/square-kilometers-to-square-meters';
import squareKilometersToSquareYards from './area/square-kilometers-to-square-yards';
import squareMetersToAcres from './area/square-meters-to-acres';
import squareMetersToHectares from './area/square-meters-to-hectares';
import squareMetersToSquareFeet from './area/square-meters-to-square-feet';
import squareMetersToSquareKilometers from './area/square-meters-to-square-kilometers';
import squareMetersToSquareYards from './area/square-meters-to-square-yards';
import squareYardsToAcres from './area/square-yards-to-acres';
import squareYardsToHectares from './area/square-yards-to-hectares';
import squareYardsToSquareFeet from './area/square-yards-to-square-feet';
import squareYardsToSquareKilometers from './area/square-yards-to-square-kilometers';
import squareYardsToSquareMeters from './area/square-yards-to-square-meters';
declare const _default: {
    acresToHectares: typeof acresToHectares;
    acresToSquareFeet: typeof acresToSquareFeet;
    acresToSquareKilometers: typeof acresToSquareKilometers;
    acresToSquareMeters: typeof acresToSquareMeters;
    acresToSquareYards: typeof acresToSquareYards;
    hectaresToAcres: typeof hectaresToAcres;
    hectaresToSquareFeet: typeof hectaresToSquareFeet;
    hectaresToSquareKilometers: typeof hectaresToSquareKilometers;
    hectaresToSquareMeters: typeof hectaresToSquareMeters;
    hectaresToSquareYards: typeof hectaresToSquareYards;
    squareFeetToAcres: typeof squareFeetToAcres;
    squareFeetToHectares: typeof squareFeetToHectares;
    squareFeetToSquareKilometers: typeof squareFeetToSquareKilometers;
    squareFeetToSquareMeters: typeof squareFeetToSquareMeters;
    squareFeetToSquareYards: typeof squareFeetToSquareYards;
    squareKilometersToAcres: typeof squareKilometersToAcres;
    squareKilometersToHectares: typeof squareKilometersToHectares;
    squareKilometersToSquareFeet: typeof squareKilometersToSquareFeet;
    squareKilometersToSquareMeters: typeof squareKilometersToSquareMeters;
    squareKilometersToSquareYards: typeof squareKilometersToSquareYards;
    squareMetersToAcres: typeof squareMetersToAcres;
    squareMetersToHectares: typeof squareMetersToHectares;
    squareMetersToSquareFeet: typeof squareMetersToSquareFeet;
    squareMetersToSquareKilometers: typeof squareMetersToSquareKilometers;
    squareMetersToSquareYards: typeof squareMetersToSquareYards;
    squareYardsToAcres: typeof squareYardsToAcres;
    squareYardsToHectares: typeof squareYardsToHectares;
    squareYardsToSquareFeet: typeof squareYardsToSquareFeet;
    squareYardsToSquareKilometers: typeof squareYardsToSquareKilometers;
    squareYardsToSquareMeters: typeof squareYardsToSquareMeters;
};
export default _default;
