import newtonToDyne from './force/newton-to-dyne';
import newtonToKilopond from './force/newton-to-kilopond';
import newtonToPoundal from './force/newton-to-poundal';
import newtonToPoundForce from './force/newton-to-pound-force';
import newtonToOunceForce from './force/newton-to-ounce-force';
import dyneToNewton from './force/dyne-to-newton';
import dyneToKilopond from './force/dyne-to-kilopond';
import dyneToPoundal from './force/dyne-to-poundal';
import dyneToPoundForce from './force/dyne-to-pound-force';
import dyneToOunceForce from './force/dyne-to-ounce-force';
import kilopondToNewton from './force/kilopond-to-newton';
import kilopondToDyne from './force/kilopond-to-dyne';
import kilopondToPoundal from './force/kilopond-to-poundal';
import kilopondToPoundForce from './force/kilopond-to-pound-force';
import kilopondToOunceForce from './force/kilopond-to-ounce-force';
import poundalToNewton from './force/poundal-to-newton';
import poundalToDyne from './force/poundal-to-dyne';
import poundalToKilopond from './force/poundal-to-kilopond';
import poundalToPoundForce from './force/poundal-to-pound-force';
import poundalToOunceForce from './force/poundal-to-ounce-force';
import poundForceToNewton from './force/pound-force-to-newton';
import poundForceToDyne from './force/pound-force-to-dyne';
import poundForceToKilopond from './force/pound-force-to-kilopond';
import poundForceToPoundal from './force/pound-force-to-poundal';
import poundForceToOunceForce from './force/pound-force-to-ounce-force';
import ounceForceToNewton from './force/ounce-force-to-newton';
import ounceForceToDyne from './force/ounce-force-to-dyne';
import ounceForceToKilopond from './force/ounce-force-to-kilopond';
import ounceForceToPoundal from './force/ounce-force-to-poundal';
import ounceForceToPoundForce from './force/ounce-force-to-pound-force';
declare const _default: {
    newtonToDyne: typeof newtonToDyne;
    newtonToKilopond: typeof newtonToKilopond;
    newtonToPoundal: typeof newtonToPoundal;
    newtonToPoundForce: typeof newtonToPoundForce;
    newtonToOunceForce: typeof newtonToOunceForce;
    dyneToNewton: typeof dyneToNewton;
    dyneToKilopond: typeof dyneToKilopond;
    dyneToPoundal: typeof dyneToPoundal;
    dyneToPoundForce: typeof dyneToPoundForce;
    dyneToOunceForce: typeof dyneToOunceForce;
    kilopondToNewton: typeof kilopondToNewton;
    kilopondToDyne: typeof kilopondToDyne;
    kilopondToPoundal: typeof kilopondToPoundal;
    kilopondToPoundForce: typeof kilopondToPoundForce;
    kilopondToOunceForce: typeof kilopondToOunceForce;
    poundalToNewton: typeof poundalToNewton;
    poundalToDyne: typeof poundalToDyne;
    poundalToKilopond: typeof poundalToKilopond;
    poundalToPoundForce: typeof poundalToPoundForce;
    poundalToOunceForce: typeof poundalToOunceForce;
    poundForceToNewton: typeof poundForceToNewton;
    poundForceToDyne: typeof poundForceToDyne;
    poundForceToKilopond: typeof poundForceToKilopond;
    poundForceToPoundal: typeof poundForceToPoundal;
    poundForceToOunceForce: typeof poundForceToOunceForce;
    ounceForceToNewton: typeof ounceForceToNewton;
    ounceForceToDyne: typeof ounceForceToDyne;
    ounceForceToKilopond: typeof ounceForceToKilopond;
    ounceForceToPoundal: typeof ounceForceToPoundal;
    ounceForceToPoundForce: typeof ounceForceToPoundForce;
};
export default _default;
