import hertzToKilohertz from './frequency/hertz-to-kilohertz';
import hertzToMegahertz from './frequency/hertz-to-megahertz';
import hertzToGigahertz from './frequency/hertz-to-gigahertz';
import hertzToRevolutionsPerMinute from './frequency/hertz-to-revolutions-per-minute';
import kilohertzToHertz from './frequency/kilohertz-to-hertz';
import kilohertzToMegahertz from './frequency/kilohertz-to-megahertz';
import kilohertzToGigahertz from './frequency/kilohertz-to-gigahertz';
import kilohertzToRevolutionsPerMinute from './frequency/kilohertz-to-revolutions-per-minute';
import megahertzToHertz from './frequency/megahertz-to-hertz';
import megahertzToKilohertz from './frequency/megahertz-to-kilohertz';
import megahertzToGigahertz from './frequency/megahertz-to-gigahertz';
import megahertzToRevolutionsPerMinute from './frequency/megahertz-to-revolutions-per-minute';
import gigahertzToHertz from './frequency/gigahertz-to-hertz';
import gigahertzToKilohertz from './frequency/gigahertz-to-kilohertz';
import gigahertzToMegahertz from './frequency/gigahertz-to-megahertz';
import gigahertzToRevolutionsPerMinute from './frequency/gigahertz-to-revolutions-per-minute';
import revolutionsPerMinuteToHertz from './frequency/revolutions-per-minute-to-hertz';
import revolutionsPerMinuteToKilohertz from './frequency/revolutions-per-minute-to-kilohertz';
import revolutionsPerMinuteToMegahertz from './frequency/revolutions-per-minute-to-megahertz';
import revolutionsPerMinuteToGigahertz from './frequency/revolutions-per-minute-to-gigahertz';
declare const _default: {
    hertzToKilohertz: typeof hertzToKilohertz;
    hertzToMegahertz: typeof hertzToMegahertz;
    hertzToGigahertz: typeof hertzToGigahertz;
    hertzToRevolutionsPerMinute: typeof hertzToRevolutionsPerMinute;
    kilohertzToHertz: typeof kilohertzToHertz;
    kilohertzToMegahertz: typeof kilohertzToMegahertz;
    kilohertzToGigahertz: typeof kilohertzToGigahertz;
    kilohertzToRevolutionsPerMinute: typeof kilohertzToRevolutionsPerMinute;
    megahertzToHertz: typeof megahertzToHertz;
    megahertzToKilohertz: typeof megahertzToKilohertz;
    megahertzToGigahertz: typeof megahertzToGigahertz;
    megahertzToRevolutionsPerMinute: typeof megahertzToRevolutionsPerMinute;
    gigahertzToHertz: typeof gigahertzToHertz;
    gigahertzToKilohertz: typeof gigahertzToKilohertz;
    gigahertzToMegahertz: typeof gigahertzToMegahertz;
    gigahertzToRevolutionsPerMinute: typeof gigahertzToRevolutionsPerMinute;
    revolutionsPerMinuteToHertz: typeof revolutionsPerMinuteToHertz;
    revolutionsPerMinuteToKilohertz: typeof revolutionsPerMinuteToKilohertz;
    revolutionsPerMinuteToMegahertz: typeof revolutionsPerMinuteToMegahertz;
    revolutionsPerMinuteToGigahertz: typeof revolutionsPerMinuteToGigahertz;
};
export default _default;
