import kelvinToFahrenheit from './temperature/kelvin-to-fahrenheit';
import kelvinToCelsius from './temperature/kelvin-to-celsius';
import kelvinToRankine from './temperature/kelvin-to-rankine';
import fahrenheitToKelvin from './temperature/fahrenheit-to-kelvin';
import fahrenheitToCelsius from './temperature/fahrenheit-to-celsius';
import fahrenheitToRankine from './temperature/fahrenheit-to-rankine';
import celsiusToFahrenheit from './temperature/celsius-to-fahrenheit';
import celsiusToKelvin from './temperature/celsius-to-kelvin';
import celsiusToRankine from './temperature/celsius-to-rankine';
import rankineToKelvin from './temperature/rankine-to-kelvin';
import rankineToFahrenheit from './temperature/rankine-to-fahrenheit';
import rankineToCelsius from './temperature/rankine-to-celsius';
declare const _default: {
    kelvinToFahrenheit: typeof kelvinToFahrenheit;
    kelvinToCelsius: typeof kelvinToCelsius;
    kelvinToRankine: typeof kelvinToRankine;
    fahrenheitToKelvin: typeof fahrenheitToKelvin;
    fahrenheitToCelsius: typeof fahrenheitToCelsius;
    fahrenheitToRankine: typeof fahrenheitToRankine;
    celsiusToFahrenheit: typeof celsiusToFahrenheit;
    celsiusToKelvin: typeof celsiusToKelvin;
    celsiusToRankine: typeof celsiusToRankine;
    rankineToKelvin: typeof rankineToKelvin;
    rankineToFahrenheit: typeof rankineToFahrenheit;
    rankineToCelsius: typeof rankineToCelsius;
};
export default _default;
