import nanosecondsToMicroseconds from './time/nanoseconds-to-microseconds';
import nanosecondsToMilliseconds from './time/nanoseconds-to-milliseconds';
import nanosecondsToSeconds from './time/nanoseconds-to-seconds';
import nanosecondsToMinutes from './time/nanoseconds-to-minutes';
import nanosecondsToHours from './time/nanoseconds-to-hours';
import nanosecondsToDays from './time/nanoseconds-to-days';
import microsecondsToNanoseconds from './time/microseconds-to-nanoseconds';
import microsecondsToMilliseconds from './time/microseconds-to-milliseconds';
import microsecondsToSeconds from './time/microseconds-to-seconds';
import microsecondsToMinutes from './time/microseconds-to-minutes';
import microsecondsToHours from './time/microseconds-to-hours';
import microsecondsToDays from './time/microseconds-to-days';
import millisecondsToNanoseconds from './time/milliseconds-to-nanoseconds';
import millisecondsToMicroseconds from './time/milliseconds-to-microseconds';
import millisecondsToSeconds from './time/milliseconds-to-seconds';
import millisecondsToMinutes from './time/milliseconds-to-minutes';
import millisecondsToHours from './time/milliseconds-to-hours';
import millisecondsToDays from './time/milliseconds-to-days';
import secondsToNanoseconds from './time/seconds-to-nanoseconds';
import secondsToMicroseconds from './time/seconds-to-microseconds';
import secondsToMilliseconds from './time/seconds-to-milliseconds';
import secondsToMinutes from './time/seconds-to-minutes';
import secondsToHours from './time/seconds-to-hours';
import secondsToDays from './time/seconds-to-days';
import minutesToNanoseconds from './time/minutes-to-nanoseconds';
import minutesToMicroseconds from './time/minutes-to-microseconds';
import minutesToMilliseconds from './time/minutes-to-milliseconds';
import minutesToSeconds from './time/minutes-to-seconds';
import minutesToHours from './time/minutes-to-hours';
import minutesToDays from './time/minutes-to-days';
import hoursToNanoseconds from './time/hours-to-nanoseconds';
import hoursToMicroseconds from './time/hours-to-microseconds';
import hoursToMilliseconds from './time/hours-to-milliseconds';
import hoursToSeconds from './time/hours-to-seconds';
import hoursToMinutes from './time/hours-to-minutes';
import hoursToDays from './time/hours-to-days';
import daysToNanoseconds from './time/days-to-nanoseconds';
import daysToMicroseconds from './time/days-to-microseconds';
import daysToMilliseconds from './time/days-to-milliseconds';
import daysToSeconds from './time/days-to-seconds';
import daysToMinutes from './time/days-to-minutes';
import daysToHours from './time/days-to-hours';
declare const _default: {
    nanosecondsToMicroseconds: typeof nanosecondsToMicroseconds;
    nanosecondsToMilliseconds: typeof nanosecondsToMilliseconds;
    nanosecondsToSeconds: typeof nanosecondsToSeconds;
    nanosecondsToMinutes: typeof nanosecondsToMinutes;
    nanosecondsToHours: typeof nanosecondsToHours;
    nanosecondsToDays: typeof nanosecondsToDays;
    microsecondsToNanoseconds: typeof microsecondsToNanoseconds;
    microsecondsToMilliseconds: typeof microsecondsToMilliseconds;
    microsecondsToSeconds: typeof microsecondsToSeconds;
    microsecondsToMinutes: typeof microsecondsToMinutes;
    microsecondsToHours: typeof microsecondsToHours;
    microsecondsToDays: typeof microsecondsToDays;
    millisecondsToNanoseconds: typeof millisecondsToNanoseconds;
    millisecondsToMicroseconds: typeof millisecondsToMicroseconds;
    millisecondsToSeconds: typeof millisecondsToSeconds;
    millisecondsToMinutes: typeof millisecondsToMinutes;
    millisecondsToHours: typeof millisecondsToHours;
    millisecondsToDays: typeof millisecondsToDays;
    secondsToNanoseconds: typeof secondsToNanoseconds;
    secondsToMicroseconds: typeof secondsToMicroseconds;
    secondsToMilliseconds: typeof secondsToMilliseconds;
    secondsToMinutes: typeof secondsToMinutes;
    secondsToHours: typeof secondsToHours;
    secondsToDays: typeof secondsToDays;
    minutesToNanoseconds: typeof minutesToNanoseconds;
    minutesToMicroseconds: typeof minutesToMicroseconds;
    minutesToMilliseconds: typeof minutesToMilliseconds;
    minutesToSeconds: typeof minutesToSeconds;
    minutesToHours: typeof minutesToHours;
    minutesToDays: typeof minutesToDays;
    hoursToNanoseconds: typeof hoursToNanoseconds;
    hoursToMicroseconds: typeof hoursToMicroseconds;
    hoursToMilliseconds: typeof hoursToMilliseconds;
    hoursToSeconds: typeof hoursToSeconds;
    hoursToMinutes: typeof hoursToMinutes;
    hoursToDays: typeof hoursToDays;
    daysToNanoseconds: typeof daysToNanoseconds;
    daysToMicroseconds: typeof daysToMicroseconds;
    daysToMilliseconds: typeof daysToMilliseconds;
    daysToSeconds: typeof daysToSeconds;
    daysToMinutes: typeof daysToMinutes;
    daysToHours: typeof daysToHours;
};
export default _default;
