import kilogramsToPounds from './weight/kilograms-to-pounds';
import kilogramsToStones from './weight/kilograms-to-stones';
import kilogramsToTonnes from './weight/kilograms-to-tonnes';
import poundsToKilograms from './weight/pounds-to-kilograms';
import poundsToStones from './weight/pounds-to-stones';
import poundsToTonnes from './weight/pounds-to-tonnes';
import stonesToKilograms from './weight/stones-to-kilograms';
import stonesToPounds from './weight/stones-to-pounds';
import stonesToTonnes from './weight/stones-to-tonnes';
import tonnesToKilograms from './weight/tonnes-to-kilograms';
import tonnesToPounds from './weight/tonnes-to-pounds';
import tonnesToStones from './weight/tonnes-to-stones';
declare const _default: {
    kilogramsToPounds: typeof kilogramsToPounds;
    kilogramsToStones: typeof kilogramsToStones;
    kilogramsToTonnes: typeof kilogramsToTonnes;
    poundsToKilograms: typeof poundsToKilograms;
    poundsToStones: typeof poundsToStones;
    poundsToTonnes: typeof poundsToTonnes;
    stonesToKilograms: typeof stonesToKilograms;
    stonesToPounds: typeof stonesToPounds;
    stonesToTonnes: typeof stonesToTonnes;
    tonnesToKilograms: typeof tonnesToKilograms;
    tonnesToPounds: typeof tonnesToPounds;
    tonnesToStones: typeof tonnesToStones;
};
export default _default;
